import React from 'react';
import { TestType } from '../types';

interface DashboardProps {
  onStartTest: (testType: TestType) => void;
}

const InfoIcon: React.FC = () => (
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
        <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
    </svg>
);

const TestCard: React.FC<{ title: TestType; description: string; duration: string; onClick: () => void; }> = ({ title, description, duration, onClick }) => (
    <div className="bg-white dark:bg-slate-800 rounded-lg shadow-lg p-6 flex flex-col hover:shadow-xl transition-shadow duration-300">
        <div className="flex-grow">
            <h3 className="text-xl font-bold text-primary-600 dark:text-primary-400 mb-2">{title}</h3>
            <p className="text-slate-600 dark:text-slate-300 mb-4">{description}</p>
        </div>
        <div className="flex justify-between items-center text-sm text-slate-500 dark:text-slate-400 mb-4">
            <span className="flex items-center space-x-1">
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-5 h-5">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                <span>{duration}</span>
            </span>
        </div>
        <button onClick={onClick} className="w-full bg-primary-600 text-white font-semibold py-2 px-4 rounded-md hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 dark:focus:ring-offset-slate-900 transition-colors duration-300">
            Start Test
        </button>
    </div>
);

const Dashboard: React.FC<DashboardProps> = ({ onStartTest }) => {
  return (
    <div className="max-w-5xl mx-auto">
        <div className="text-center mb-8">
            <h2 className="text-3xl font-extrabold text-slate-900 dark:text-white">Welcome to your Aptis Practice</h2>
            <p className="mt-2 text-lg text-slate-600 dark:text-slate-300">Choose a section below to begin your test.</p>
        </div>

        <div className="p-4 mb-8 bg-blue-100 dark:bg-slate-700/50 border-l-4 border-blue-500 text-blue-800 dark:text-blue-200 rounded-r-lg flex items-start space-x-3">
            <div className="shrink-0 pt-0.5">
                <InfoIcon />
            </div>
            <div>
                <h4 className="font-bold">How it works</h4>
                <p>Each test is generated by AI to give you a unique practice experience every time. The questions are designed to match the B1/B2 CEFR level required for the General Aptis exam.</p>
            </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <TestCard 
                title={TestType.GRAMMAR_VOCABULARY} 
                description="Tests your knowledge of English grammar and vocabulary with 25 multiple-choice questions." 
                duration="12 minutes"
                onClick={() => onStartTest(TestType.GRAMMAR_VOCABULARY)} 
            />
            <TestCard 
                title={TestType.READING} 
                description="Assess your reading comprehension skills with passages and questions, simulating the real exam format." 
                duration="35 minutes"
                onClick={() => onStartTest(TestType.READING)} 
            />
             <TestCard 
                title={TestType.LISTENING} 
                description="Listen to audio and answer questions to test your comprehension of spoken English." 
                duration="40 minutes"
                onClick={() => onStartTest(TestType.LISTENING)} 
            />
            <TestCard 
                title={TestType.WRITING} 
                description="Practice your written English, from filling out forms to writing formal emails, across several tasks." 
                duration="50 minutes"
                onClick={() => onStartTest(TestType.WRITING)} 
            />
            <TestCard 
                title={TestType.SPEAKING} 
                description="Test your spoken English by responding to prompts and recording your answers. Requires a microphone." 
                duration="12 minutes"
                onClick={() => onStartTest(TestType.SPEAKING)} 
            />
        </div>
    </div>
  );
};

export default Dashboard;
